AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  goldapi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /gold-api
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
      Layers:
        - >-
          arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-python38-graphene:2
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      PackageType: Zip
      Policies:
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::boatregister/gold/*
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
            Resource: arn:aws:logs:eu-west-1:651845762820:*
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - >-
                arn:aws:logs:eu-west-1:651845762820:log-group:/aws/lambda/gold-api:*
