AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: GraphQL API for accessing OGA Member Data.
Resources:
  goldpoll:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: gold-api
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      InlineCode: >-
        def lambda_handler(event, context):
          print('Checking {} at {}...'.format(SITE, event['time']))
      Description: GraphQL API for accessing OGA Member Data
      MemorySize: 128
      Timeout: 60
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /gold-api
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
      Policies:
        - S3CrudPolicy:
            BucketName: boatregister
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      PackageType: Zip