name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.6.1'
      - name: package
        run: |
          poetry run pip install -t dist .
          cd dist
          zip -x 'gold_api' -r ../lambda.zip .
          cd gold_api
          zip ../../lambda.zip .
      - name: cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: deploy
        run: |
          aws lambda update-function-code --function-name gold-api --zip-file fileb://lambda.zip
